# Change these first
owner: phixer # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: phixer.net
    url: https://www.phixer.net
  - name: ent.phixer.net
    url: https://ent.phixer.net
  - name: app.phixer.net
    url: https://app.phixer.net
  - name: redfin.phixer.net
    url: https://redfin.phixer.net
  - name: hdestates.phixer.net
    url: https://hdestates.phixer.net
  - name: photoport.net
    url: https://photoport.net
    
assignees: # Users to assign downtime issues (optional)
  - rad182
  
status-website:
  cname: status.phixer.net
  name: Phixer Status
  apiBaseUrl: https://api.github.com
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
